Repository frenck/awesome-home-assistant, pull requests merged in 2022-06, with the labels that each got.

#213 Add mention of new Raspberry Pi Status Card
  README.md
Labels: 💖 new

#383 Update JupyterLab add-on information
  README.md
Labels: ❤️‍🩹 update

#384 💖 Add Hass Hue Icons
  README.md
Labels: 💖 new

#385 💖 Add Dwains Dashboard
  README.md
Labels: 💖 new

#386 Rename components -> integrations
  README.md
Labels: ❤️‍🩹 update

#332 💖 Add WebRTC Card
  README.md
Labels: 💖 new

#387 Website improvements
  docs/css/extra.css
  mkdocs.yml
  requirements.txt
Labels: enhancement

#392 Add icon packs section
  README.md
Labels: enhancement

#393 ❤️‍🔥 Remove Google Geocode
  README.md
Labels: ❤️‍🔥 remove

#394 💖 Adds Sonoff LAN custom integration
  README.md
Labels: 💖 new

#395 💖 Add simpleicons icon pack
  README.md
Labels: 💖 new

#396 💖 Add Spotcast
  README.md
Labels: 💖 new

#397 ❤️‍🔥 Remove Swiper Card
  README.md
Labels: ❤️‍🔥 remove

#400 💖 Add The Watchman custom integration
  README.md
Labels: 💖 new
